---
title: "Take-home Exercise 1"
date: "January 20, 2025"
date-modified: "last-modified"
format: html
editor: visual
---

::: callout-note
## Creating data visualisation that is enligthening and truthful

Creating enlightening and truthful data visualizations involves focusing on accuracy, transparency, and the ability to effectively communicate insights. It's about presenting data in a way that is both informative and aesthetically pleasing, ensuring the audience can grasp the information quickly and accurately.
:::

## Overview

This handout provides the context, task, expectations and grading criteria of Take-home Exercise 1. Students must review and understand them before getting started with the take-home exercise.

## Setting the scene

A local online media company that publishes daily content on digital platforms is planning to release an article on **demographic structures and distribution of Singapore in 2024**.

## The Task

Assuming the role of the graphical editor of the media company, you are tasked to prepare **at most three data visualisation** for the article.

::: callout-important
The task will be completed in two phases:

-   Phase 1: Designing your own data visualisation.
-   Phase 2: Selecting one submission provided by your classmate, critic three good design principles and three areas for further improvement. With reference to the comment, prepare the makeover version of the data visualisation.
:::

## The Data

To accomplish the task, *Singapore Residents by Planning Area / Subzone, Single Year of Age and Sex, June 2024* dataset shares by [Department of Statistics, Singapore (DOS)](https://www.singstat.gov.sg/) should be used.

## The Designing Tool

The data should be processed by using appropriate **tidyverse** family of packages and the data visualisation must be prepared using **ggplot2** and **its extensions**.

::: callout-important
No interactive data visualisation are required.
:::

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared below.

-   A write-up of not more than **150 words** per each data visualisation, describing and discussing the patterns reveal by each visualisation prepared.

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
:::

## Submission date

::: callout-important
There are two submission deadlines for this take-home exercise, they are:

-   Phase 1: 4th May 2025 mid-night ~~12:00am~~ 11:59pm.
-   Phase 2: 11th May 2025 mid-night ~~12:00am~~ 11:59pm
:::

## Learning from senior

-   [KYLIE TAN JING YI](https://akalestale.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TOA ZI YING JANET](https://janettoaisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LEW YING ZHEN SERENA](https://isss608-spacebun.netlify.app/take-home_ex/take-home_ex1/take-home_ex1)
-   [SENG JING YI](https://jingyi-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [JAYA GEORGE](https://isss608-jayageorge.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)

## Peer Learning

-   [ANDRE ONG JIA KANG](https://isss608-ay2025-aprilterm.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [CALVIN TAN SONG HAO](https://isss608-ay2024-25t3.netlify.app/take-home_ex/take-home_ex01-1/take-home_ex01-1)
-   [CHAN HAN JIE](https://isss608-ay2024-25t3-chj.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [CHIAM SHUNZHONG DAVID](https://isss608-davidchiam.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [DO QUYNH TRANG](https://isss608-ay2425-qtd.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [ENRICO SEBASTIAN ENRICO SEBASTIAN DANUSANTOSO](https://iss608-vaa.netlify.app/take-home_ex/take-home_ex01/take%20home%20exercise%201)
-   [EVANGELINE OLIVIA SIDIHARTO](https://isss608-evangelineolivia.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [FU YILIN](https://isss608-ay2025t2.netlify.app/Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html)
-   [GOH YI FANG](https://isss608-yfgoh.netlify.app/take-home_ex/take-home_ex1/take-home_ex01)
-   [HAO LIU](https://isss608-ay2025-hliu.netlify.app/take_home_exercise/take_home_exercise01/take_home_exercise01)
-   [HUANG PENGXIN](https://pengxinhuang.netlify.app/take-home_ex01/)
-   [HUANG ZIHAN](https://isss608-hzh.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [JESSE EMMANUEL LUCAS](https://isss608-ay2025.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LAU JIA YI](https://isss608-ay2024-25apr-jylau.netlify.app/t1/takehome_ex01)
-   [LI JIANYI](https://isss608-jianyivaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LI YUQUAN](https://isss608-2025-yuquan.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIAW YING TING CELIN](https://isss608celin.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIM KAH SIEW BELINDA](https://isss608-ay2024-25t3-belindalim.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIU CHIH-YUAN](https://cabbage-wonderland.netlify.app/takehome_ex/takehome_ex01/takehome_ex01)
-   [LU LINSEN](https://isss608-ay2024-25t2.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LUO YUMING](https://isss608vaa.netlify.app/take-home_exercise/take-home_ex01/take-home_ex01)
-   [MARGA THURA](https://isss608-ay2024-2025.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [MIN HTET AUNG](https://isss608-minhtetaung.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [NG JIN YAO](https://isss608-blessmebellburve.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [NG WEE TINN SHERMAINN](https://isss608-sherm.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [NGUYEN NGUYEN HA](https://summernguyenn.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [NGUYEN PHUONG HOA](https://isss608-ay2024-25t.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [NOR HENDRA BIN ABDUL RAHMAN](https://norhendra-isss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [PATRICIA TRISNO](https://isss608-ay2024-25t2-pat.netlify.app/take-home_exercise/take-home_ex01/take-home_exercise01)
-   [PENG HSIAO-YUAN](https://lesteronthecouchisss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [RAJESH BABU SANTIGARI](https://isss608vaarajesh01.netlify.app/takehomeexercises/take_homeexercise1/take_homeexercise1)
-   [SANDRA JACOB](https://sandrajacob-isss608.netlify.app/takehome_exercises/takehome_ex01/takehomeex01)
-   [SARIYANTI HARTIONO](https://isss608-shar.netlify.app/take-home_ex/take-home_ex_1/take-home_ex01)
-   [STEFANIE FELICIA](https://isss608-ay2025-april.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TA NGUYEN THAO NGUYEN](https://isss608-cindy.netlify.app/take-home_exercise/take-home_ex01/take-home_ex01a)
-   [TAI QIUYAN](https://isss608-ay2025-qiuyan.netlify.app/takehome_ex/takehome_ex01/takehome_ex01)
-   [TAI YU YING](https://whereinsightbegins.netlify.app/take-home_ex/take-home_ex01/take-homeexercise1)
-   [TAN WENYING AUDREY](https://isss608-ay2024-25-dreytwy.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TEO WEE SIANG ROY](https://iss608-first-session.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [VANESSA RIADI](https://isss608-vriadi.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [WANG ANQI](https://isss608-25t3-anqi.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [WANG SHENSI](https://wshensi.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [XU XINYI](https://xinyixu.netlify.app/take-home_exercise/take-home_ex01/take-home_exercise01)
-   [YANG LU](https://isss608yanglu.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [YANG YAYONG](https://isss608-vaa-yangyayong.netlify.app/take-home_exercise/take-home_ex01/take-home_ex01)
-   [YUAN YIHAO]()
-   [ZHANG JINGHAN](https://isss608-visualanalytics.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [ZHANG XUERONG]()
